/**
 * Centralized DOM element dictionary for the 3D Flag Configurator.
 * Elements are resolved dynamically or cached upon import.
 */
export const dom = {
    canvasContainer: document.getElementById('canvas-container'),
    prefBtn: document.getElementById('pref-btn'),
    prefBtnText: document.getElementById('pref-btn-text'),
    prefDropdown: document.getElementById('pref-dropdown'),
    prefLangList: document.getElementById('pref-lang-list'),
    prefCurrencyList: document.getElementById('pref-currency-list'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingText: document.getElementById('loading-text'),
    uiPanel: document.getElementById('ui-panel'),
    pocketColor: document.getElementById('pocket-color'),
    pocketColorTrigger: document.getElementById('pocket-color-trigger'),
    pocketColorValue: document.getElementById('pocket-color-value'),
    pocketColorSwatch: document.getElementById('pocket-color-swatch'),
    playPause: document.getElementById('play-pause'),
    generatePdf: document.getElementById('generate-pdf'),
    shareDesign: document.getElementById('share-design'),
    addToCart: document.getElementById('add-to-cart'),
    cameraWrapper: document.getElementById('camera-wrapper'),
    cameraActions: document.getElementById('camera-actions'),
    turntableToggle: document.getElementById('turntable-toggle'),
    charToggle: document.getElementById('char-toggle'),
    envToggle: document.getElementById('env-toggle'),
    envPanel: document.getElementById('env-panel'),
    envExposure: document.getElementById('env-exposure'),
    envRotate: document.getElementById('env-rotate'),
    envReset: document.getElementById('env-reset'),
    arContainer: document.getElementById('ar-container'),
    toastRegion: document.getElementById('toast-region'),
    arOverlay: document.getElementById('ar-overlay'),
    stopArBtn: document.getElementById('stop-ar-btn'),
    printingInfoBtn: document.getElementById('printing-info-btn'),
    printingInfoPopover: document.getElementById('printing-info-popover'),
    templateDownloadBtn: document.getElementById('template-download-btn'),
    templateFilename: document.getElementById('template-filename'),
    moveableTarget: document.getElementById('moveable-proxy-target'),
    btnToggleGizmo: document.getElementById('btn-toggle-gizmo'),
    gizmoToggleText: document.getElementById('gizmo-toggle-text'),
    gizmoFloatingBar: document.getElementById('gizmo-floating-bar'),
    badgeScaleVal: document.getElementById('badge-scale-val'),
    badgeRotationVal: document.getElementById('badge-rotation-val'),
    badgePanXVal: document.getElementById('badge-panX-val'),
    badgePanYVal: document.getElementById('badge-panY-val'),
    btnTransformCenter: document.getElementById('btn-transform-center'),
    gizmoBtnAccept: document.getElementById('gizmo-btn-accept'),
    gizmoBtnReject: document.getElementById('gizmo-btn-reject'),
    cameraButtons: Array.from(document.querySelectorAll('#camera-controls button'))
};

export const mobileViewportMediaQuery = window.matchMedia('(max-width: 768px) and (orientation: portrait)');
